###
GET http://localhost:4009/api/word_game?sentence=The%20dog%20jumped%20over%20the%20shipyard%20fence%20in%20Greenvillage

###
GET https://web-for-bootcamp-widget.onrender.com
Content-Type: application/json

###
GET http://localhost:4009/api/phonebill/prices?type=sms&price=0.65

###
POST http://localhost:4009/api/phonebill/localhost:4009/api/phonebill/prices
Content-Type: application/json

{
  "type": "call",
"types": "2.75"
}

###
GET http://localhost:4009//phonebill/prices
{
 "call" : "2.75",
 "sms" : "0.65"
}

###
POST http://localhost:4009/api/phonebill/total
Content-Type: application/json

{
  "bill": "call, sms, sms, call"
  
}

###
GET http://localhost:4009/api/phonebill/total?bill=call,sms,call,sms,sms


###
POST http://localhost:4009/api/phonebill/price 
Content-Type: application/json

{
  "type" : "sms",
  "price" : "2.85"
}

###
POST http://localhost:4009/api/enough
Content-Type: application/json

{
  "usage": "call,sms,call",
  "available": 54
}